#!/bin/bash
set -e

# generate the build directory
npm run build

files=$(git ls-files src | sed -e 's#^src/##' | sed -e 's#/.*$##' | sort -u)
echo $files >publish-files.log
cd build
cp -rv $files ..
cd -
