export const oldschool = {}

export const runescape = {
  bestiary: {
    endpoints: {
      beast: `http://services.runescape.com/m=itemdb_rs/bestiary/beastData.json?beastid=`,
      beastTerm: `http://services.runescape.com/m=itemdb_rs/bestiary/beastSearch.json?term=`,
      beastLetter: `http://services.runescape.com/m=itemdb_rs/bestiary/bestiaryNames.json?letter=`,
      areas: `http://services.runescape.com/m=itemdb_rs/bestiary/areaNames.json`,
      beastArea: `http://services.runescape.com/m=itemdb_rs/bestiary/areaBeasts.json?identifier=`,
      beastSlayer: `http://services.runescape.com/m=itemdb_rs/bestiary/slayerBeasts.json?identifier=`,
      beastWeakness: `http://services.runescape.com/m=itemdb_rs/bestiary/weaknessBeasts.json?identifier=`,
      beastLevel: `http://services.runescape.com/m=itemdb_rs/bestiary/levelGroup.json?identifier=`,
      slayerCategories: `http://services.runescape.com/m=itemdb_rs/bestiary/bestiary/slayerCatNames.json`,
      weaknesses: `http://services.runescape.com/m=itemdb_rs/bestiary/bestiary/weaknessNames.json`,
    },
    searchMethods: [
      "terms",
      "firstLetter",
      "area",
      "slayerCategory",
      "weakness",
      "levelRange",
    ] as const,
  },
  grandexchange: {
    endpoints: {
      category: `http://services.runescape.com/m=itemdb_rs/api/catalogue/category.json?category=`,
      categoryPrices: `http://services.runescape.com/m=itemdb_rs/api/catalogue/items.json?`,
      item: `http://services.runescape.com/m=itemdb_rs/api/catalogue/detail.json?item=`,
      itemGraph: `http://services.runescape.com/m=itemdb_rs/api/graph/`,
    },
    categories: [
      "Miscellaneous",
      "Ammo",
      "Arrows",
      "Bolts",
      "Construction materials",
      "Construction projects",
      "Cooking ingredients",
      "Costumes",
      "Crafting materials",
      "Familiars",
      "Farming produce",
      "Fletching materials",
      "Food and drink",
      "Herblore materials",
      "Hunting equipment",
      "Hunting produce",
      "Jewellery",
      "Mage armour",
      "Mage weapons",
      "Melee armour - low level",
      "Melee armour - mid level",
      "Melee armour - high level",
      "Melee weapons - low level",
      "Melee weapons - mid level",
      "Melee weapons - high level",
      "Mining and smithing",
      "Potions",
      "Prayer armour",
      "Prayer materials",
      "Range armour",
      "Range weapons",
      "Runecrafting",
      "Runes, Spells and Teleports",
      "Seeds",
      "Summoning scrolls",
      "Tools and containers",
      "Woodcutting product",
      "Pocket items",
    ],
  },
  hiscores: {
    endpoints: {
      normal: `http://services.runescape.com/m=hiscore/index_lite.ws`,
      ironman: `http://services.runescape.com/m=hiscore_ironman/index_lite.ws`,
      hardcore: `http://services.runescape.com/m=hiscore_hardcore_ironman/index_lite.ws`,
      clan: `http://services.runescape.com/m=clan-hiscores/members_lite.ws`,
    },
    activities: [
      "bounty_hunters",
      "bh_rogues",
      "dominion_tower",
      "the_crucible",
      "castle_wars_games",
      "ba_attackers",
      "ba_defenders",
      "ba_collectors",
      "ba_healers",
      "duel_tournament",
      "mobilising_armies",
      "conquest",
      "fist_of_guthix",
      "gg_resource_race",
      "gg_athletics",
      "we2_armadyl_lifetime_contribution",
      "we2_bandos_lifetime_contribution",
      "we2_armadyl_pvp_kills",
      "we2_bandos_pvp_kills",
      "heist_guard_level",
      "heist_robber_level",
      "cfp_5_game_average",
      "af15_cow_tipping",
      "af15_rats_killed_after_the_miniquest",
      "runescore",
      "clue_scrolls_easy",
      "clue_scrolls_medium",
      "clue_scrolls_hard",
      "clue_scrolls_elite",
      "clue_scrolls_master",
    ] as const,
    skills: [
      "overall",
      "attack",
      "defence",
      "strength",
      "constitution",
      "ranged",
      "prayer",
      "magic",
      "cooking",
      "woodcutting",
      "fletching",
      "fishing",
      "firemaking",
      "crafting",
      "smithing",
      "mining",
      "herblore",
      "agility",
      "thieving",
      "slayer",
      "farming",
      "runecrafting",
      "hunter",
      "construction",
      "summoning",
      "dungeoneering",
      "divination",
      "invention",
    ] as const,
  },
  runemetrics: {
    endpoints: {
      profile: `https://apps.runescape.com/runemetrics/profile/profile`,
      monthlyXp: `https://apps.runescape.com/runemetrics/xp-monthly`,
      quests: `https://apps.runescape.com/runemetrics/quests`,
    },
  },
  other: {
    totalUsers: `https://secure.runescape.com/m=account-creation-reports/rsusertotal.ws`,
  },
}
